_majesteel_socials:
    pattern:  /socials
    defaults: { _controller: MajesSocialBundle:Admin:socials }

_majesteel_instagrams:
    pattern:  /instagrams
    defaults: { _controller: MajesSocialBundle:Instagram:instagrams }

_majesteel_instagram_edit:
    pattern:  /instagram/edit/{id}
    defaults: { _controller: MajesSocialBundle:Instagram:instagramEdit, id: null }

_majesteel_instagram_access:
    pattern:  /instagram/access/{id}
    defaults: { _controller: MajesSocialBundle:Instagram:instagramAccess, id: null }

_majesteel_instagram_delete:
    pattern:  /instagram/delete/{id}
    defaults: { _controller: MajesSocialBundle:Instagram:instagramDelete, id: null }

_majesteel_instagram_api:
    pattern:  /instagram/api/{string}
    defaults: { _controller: MajesSocialBundle:Instagram:api, string: null }

_majesteel_facebooks:
    pattern:  /facebooks
    defaults: { _controller: MajesSocialBundle:Facebook:facebooks }

_majesteel_facebook_edit:
    pattern:  /facebook/edit/{id}
    defaults: { _controller: MajesSocialBundle:Facebook:facebookEdit, id: null }

_majesteel_facebook_delete:
    pattern:  /facebook/delete/{id}
    defaults: { _controller: MajesSocialBundle:Facebook:facebookDelete, id: null }

_majesteel_twitters:
    pattern:  /twitters
    defaults: { _controller: MajesSocialBundle:Twitter:twitters }

_majesteel_twitter_edit:
    pattern:  /twitter/edit/{id}
    defaults: { _controller: MajesSocialBundle:Twitter:twitterEdit, id: null }

_majesteel_twitter_delete:
    pattern:  /twitter/delete/{id}
    defaults: { _controller: MajesSocialBundle:Twitter:twitterDelete, id: null }

_majesteel_twitter_accessToken:
    pattern:  /twitter/access/{id}
    defaults: { _controller: MajesSocialBundle:Twitter:twitterAccess, id: null }

_majesteel_twitter_apireturn:
    pattern:  /twitter/apireturn
    defaults: { _controller: MajesSocialBundle:Twitter:apiReturn }